from collections.abc import Sequence
from typing import final

@final
class Match:
    def __repr__(self, /) -> str: ...
    @property
    def cigar(self, /) -> str: ...
    @property
    def cost(self, /) -> int: ...
    @property
    def pattern_end(self, /) -> int: ...
    @property
    def pattern_idx(self, /) -> int: ...
    @property
    def pattern_start(self, /) -> int: ...
    @property
    def strand(self, /) -> str: ...
    @property
    def text_end(self, /) -> int: ...
    @property
    def text_idx(self, /) -> int: ...
    @property
    def text_start(self, /) -> int: ...

@final
class Searcher:
    def __new__(cls, /, alphabet: str, rc: bool = True, alpha: float |None = None) -> Searcher: ...
    def search(self, /, pattern: bytes, text: bytes, k: int) -> list[Match]: ...
    def search_all(self, /, pattern: bytes, text: bytes, k: int) -> list[Match]: ...
    def search_many(self, /, patterns: Sequence[bytes], texts: Sequence[bytes], k: int, threads: int, mode: str) -> list[Match]: ...

def features() -> None: ...
