query_lengths   = [20, 100]
text_lengths    = [100_000]
k               = [5]
matches  = [0]
bench_iter      = [200]
alphabet        = ["dna"]
profile         = ["dna"]
rc              = ["withoutrc"]
verbose         = false
edlib = true
