name: Check Python Stubs

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  UV_VERSION: 0.8.22
  PYTHON_VERSION: 3.9

jobs:
  check-stubs:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            lib_name: libsassy.so
            stub_rustflags: ""
          - os: macos-latest
            lib_name: libsassy.dylib
            stub_rustflags: "-C link-arg=-undefined -C link-arg=dynamic_lookup"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          python-version: "${{ env.PYTHON_VERSION }}"
          enable-cache: 'true'
          cache-suffix: "${{ env.PYTHON_VERSION }}"

      - name: Use portable config
        run: mv .cargo/config-portable.toml .cargo/config.toml

      - name: Generate stubs
        run: |
          RUSTFLAGS="${{ matrix.stub_rustflags }}" cargo build --features python
          cargo run --features python-stubs --bin gen_stubs -- target/debug/${{ matrix.lib_name }}

      - name: Check stubs
        run: |
          uv run \
            --with mypy \
            sh -c 'mypy python/sassy/example_typed.py'
