name: Release

permissions:
  contents: write

on:
  push:
    # Run on v* tags pushed.
    tags:
      - "v*"
  # Allow manual triggering.
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - os: macos-14
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-multivers
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo install cargo-multivers
      - name: Build & test & rename
        run: |
          mv .cargo/config-portable.toml .cargo/config.toml

          # Test base configuration
          cargo build --no-default-features
          cargo build --profile dist
          cargo test --profile dist

          # Output artifact directory
          mkdir -p artifacts

          # For x86-64, use cargo-multivers to build a AVX2+AVX-512 combined binary.
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-gnu" ]; then
            cargo multivers --profile dist
            mv target/cargo-multivers/${{ matrix.target }}/release/sassy artifacts/sassy-${{ matrix.target }}
          else
            mv target/dist/sassy artifacts/sassy-${{ matrix.target }}
          fi

      - uses: actions/upload-artifact@v6
        with:
          name: build-${{ matrix.os }}
          path: artifacts

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release_artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_artifacts/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
